### ISSUE TITLE
Update or replace django-treebeard

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#11]
We use the package [django-treebeard](https://github.com/django-treebeard/django-treebeard) in edx/ecommerce, edx/portal-designer. It hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by natabene** [comment]
@idegtiarov Thanks so much for picking this up, please keep us posted.

**Comment by jmbowman** [comment]
The maintainer replied in the issue above stating that the current release (already used in both ecommerce and portal-designer) should work with Django 3.2, it was only the test suite that was updated since then.  I'll go ahead and close this and update our dependency tracking data accordingly.  Thanks @idegtiarov for getting that clarified!
