### ISSUE TITLE
Update or replace django-jenkins

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#19]
We use the package [django-jenkins](https://github.com/kmmbvnr/django-jenkins) in edx/openedxstats. This package was last released in 2016 and last commit was in 2017. It hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by jmbowman** [comment]
I think she's still out for another day or two, but I can go ahead and assign it to you.  Thanks for looking into this!

**Comment by jfavellar90** [comment]
@jmbowman hi, I already reviewed this dependency a bit, and before committing to a code refactoring, I'm evaluating the possibility of removing the package.  However, I'm not pretty sure how it is being used inside https://github.com/edx/openedxstats.

A quick [search in the repo](https://github.com/edx/openedxstats/search?q=jenkins) does not display something relevant apart from the dependency definition in the requirements file and a GitHub actions operation not related to `django-jenkins`.
The dependency is not even included in production nor testing requirements, and it is not included in the app `INSTALLED_APPS setting`, which reinforces the possibility of deleting it. To be 100% sure I ask you for guidance on who to contact in order to get clarification on this matter.

@nedbat @awais786 hi, I'm tagging you since you were working on the `openedxstats` repo recently and maybe you guys have a better insight into how `django-jenkins` is used.

**Comment by awais786** [comment]
We have already merged `django3.2` upgrade PR in openedxstats. Openedxstats already using `githubactions` so I don't think we need this package any more. Also we should remove this from repo.

@nedbat Please let me know if you any concerns ?

**Comment by jfavellar90** [comment]
Hey, @nedbat just doing a follow-up on this issue. Please let us know your thoughts on this matter when you have the chance.

**Comment by nedbat** [comment]
openedxstats no longer installs django-jenkins.  I've made a pull request to get rid of the obsolete requirements files that still mentioned it: https://github.com/edx/openedxstats/pull/116.

**Comment by jfavellar90** [comment]
Thanks for your reply @nedbat. I think we can mark this TODO as DONE once the PR https://github.com/edx/openedxstats/pull/116 gets merged.

**Comment by nedbat** [comment]
It's merged now.

**Comment by jfavellar90** [comment]
@natabene I moved this one to Done status since there's no longer dependency on django-jenkins

**Comment by natabene** [comment]
@jfavellar90 Thank you!
