### ISSUE TITLE
Update or replace django-taggit-autosuggest

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#38]
We use the package [django-taggit-autosuggest](https://bitbucket.org/fabian/django-taggit-autosuggest) in edx/course-discovery. This package isn't maintained anymore and it hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by regisb** [comment]
I suggested to the django-taggit maintainers that the project be vendored in (see [this conversation](https://github.com/jazzband/django-taggit/issues/33)). If they agree, we would be able to get rid of the django-taggit-autosuggests dependency and just depend on the latest release of django-taggit.

Whatever the solution we end up with, this issue can be assigned to me.

**Comment by natabene** [comment]
@regisb Thank you so much for picking this up and looking into it.

**Comment by regisb** [comment]
Given that I received no feedback to my question in the upstream repo, I think we should move along without the help of jazzband.



1. We get rid of the autosuggest package and lose the autocomplete functionality.
2. We fork django-taggit-autosuggest, make it compatible with Django 3.2 and install from our fork.

As far as I understand, the autosuggestion functionality is mostly used in the Course Discovery administration page. First, create a few tags "pouac" and "pouac2" at /admin/taggit/tag/. Then, edit one of the courses at /admin/course_metadata/course/. In the "tags" section, django-taggit-autosuggest offers a nifty drop-down:

![taggit-autosuggest](https://user-images.githubusercontent.com/44319/135070930-280e3473-4418-41ad-a58e-defff965e35c.png)

I think that this is a convenient feature that should not be dropped. Also, reverting migrations to stop using the TaggableManager looks like a difficult problem.

The upstream project was forked by quite a few people; the most recently updated one is https://github.com/iarp/django-taggit-autosuggest
I tested this fork with Django 2.2 and it is working. I suggest that we install django-taggit-autosuggest from this repo. Author seems responsive, so if we were to encounter any issue we would be able to open PRs.

If you agree with this approach I can open a PR.

**Comment by natabene** [comment]
@Jawayria @awais786 Could you please review the proposed approach?

**Comment by awais786** [comment]
@regisb did you get a chance to test `django-taggit-autosuggest` with django32 ? I am trying to check it with discovery (django32) and it seems working for me.  May be I did't hit the right testing scenario just added some tags and loaded them back. 

If there are any issues I will go with your suggested fork https://github.com/iarp/django-taggit-autosuggest but we have to fork this inside edx org. Does it make sense ?

**Comment by regisb** [comment]
> did you get a chance to test django-taggit-autosuggest with django32 ?

No, I assumed it was simply not working. Looking at the upgrade commit (https://github.com/iarp/django-taggit-autosuggest/commit/3a1f8b69727e6a42b414ce084e9954bc96310350), it looks like it's only the demo project that needs to be upgraded. So I guess it might be compatible with Django 3.2.

Why was this package flagged for incompatibility with Django 3.2 in the first place? @jmbowman can you explain how you detected django-taggit-autosuggest?

> I am trying to check it with discovery (django32) and it seems working for me. May be I did't hit the right testing scenario just added some tags and loaded them back.

If this use case worked for you, then I think we should be fine, because this is the only place where autosuggestion is actually used (as far as I know).

> If there are any issues I will go with your suggested fork https://github.com/iarp/django-taggit-autosuggest but we have to fork this inside edx org. Does it make sense ?

Why would edX have to fork it? I'm not sure I understand.

I'm not sure what we should do. If this package works for us, then we don't _have_ to replace it. On the other hand, we could preemptively switch to a fork, such that future Django releases cause us less trouble. I guess I would lean towards shifting to a fork -- but I don't have a very strong opinion on this.

**Comment by awais786** [comment]
@regisb The issue was created because package is missing `django32` testing and any compatibility information.

Recently I have replaced `django-require` with this fork https://github.com/edx/django-require. I think the purpose of this forking inside `edx` is to make sure it remains available and not get deleted or abandoned by the owner.

**Comment by regisb** [comment]
OK so what should we do? Personally I'm not so excited by the idea of forking a fork. So I guess I would just stick with the older package. But then again, I don't have a very strong opinion on this.

**Comment by awais786** [comment]
I will use the existing package with `django32` and in case of any issue will move to the fork.

**Comment by regisb** [comment]
Sounds good! So I guess we can close this issue?

**Comment by awais786** [comment]
@natabene you can close this. I will test the existing version with django32.
