### ISSUE TITLE
Update or replace django-ratelimit

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#41]
We use the package [django-ratelimit](https://github.com/jsocol/django-ratelimit) in edx/credentials, edx/edx-platform. It hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by mariajgrimaldi** [comment]
Hello @natabene, I hope you're doing great! 

I'll be looking into this issue soon. Would you assign it to me?

**Comment by natabene** [comment]
@mariajgrimaldi Thank you very much for volunteering with this, highly appreciated. I will assign right away, please let me know once this is done.

**Comment by mahyard** [comment]
Hi @mariajgrimaldi 
Do you mind if I take this?
I'm a bit familiar with django-ratelimit source code and I think I'm able to handle it

**Comment by mariajgrimaldi** [comment]
Oh well, of course. Go ahead!

**Comment by Andrew-Chen-Wang** [comment]
Hi all. I've updated the CI to show that django-ratelimit, without any modifications, has  a complete test suite for Django 3.2 + main and Python 3.6+. Thanks @mahyard for bringing this back up after I forgot about it 😅 https://github.com/Andrew-Chen-Wang/django-ratelimit/actions/runs/1163763411

**Comment by jsocol** [comment]
Hi all, maintainer of django-ratelimit here. One thing I want to flag is that the next release of django_ratelimit will be a major version bump that changes the package name for imports, from `ratelimit` to `django_ratelimit` (the package is from an older, smaller time in the Python package ecosystem, when namespacing was less critical). It will also include a change in default behavior from `block=False` to `block=True`.

**Comment by natabene** [comment]
Update from the edX team: we are still looking into this, please stay tuned.

**Comment by mahyard** [comment]
I believe that in short term, we cannot expect a new release of django-ratelimit to install from PyPI. However the latest code on the package's github repostory properly works with Django 3.2 and *python-memcached* caching backend. So we would be able to install it directly from a github commit id. I know that it's not a recommended approach, though, I want to make sure whether it is OK until the next release comes out? or it's a no-no?

Note that the current release also works with django 3.2, and matches with edx-platform, but as @jmbowman said it lacks some code changes since July 2020, which I think we can ignore and wait for the next official release.

**Comment by natabene** [comment]
Ok, thank you all, closing this issue.
