### ISSUE TITLE
Update or replace zappa

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#65]
We use the package [zappa](https://github.com/Miserlou/Zappa) in edx/clamps. It hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by felipemontoya** [comment]
I did not know zappa was used anywhere in the stack, but I have used zappa before and I like it. However I could not find many references to clamps. What I have found suggests that the repo is not public.
Could you please give me a bit more info?

**Comment by jmbowman** [comment]
Thanks for calling this out.  This came up in our enumeration of Django-using dependencies because it has Trove classifiers for Django support, but it looks like our Slack bot in that private repo doesn't actually use the optional Django management command support.  So I'll go ahead and close this and update our dependency tracking data accordingly.  Still would be nice if upstream explicitly tested and supported Django 3.2.
