### ISSUE TITLE
Update or replace edx-proctoring-proctortrack

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#70]
We use the package [edx-proctoring-proctortrack](https://github.com/joshivj/edx-proctoring-proctortrack) in edx/edx-platform. It hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by pdpinch** [comment]
Is it possible for an open edX community member to work on this without a ProctorTrack account?

**Comment by natabene** [comment]
@awais786 Please help @pdpinch with this question when you have a chance.

**Comment by awais786** [comment]
@schenedx any ideas ?

**Comment by schenedx** [comment]
@pdpinch I believe edX community member can work on this without a Proctortrack Account. This is because the library in question here do not depends on django.
I looked and didn't see anything we can change on [edx-proctoring-proctortrack](https://github.com/anupdhabarde/edx-proctoring-proctortrack) that require django 3.2. I believe the django 3.2 dependency is on [edx-proctoring](https://github.com/edx/edx-proctoring/blob/master/requirements/base.txt#L38), which is not yet on Django 3.2. My team in edX will make sure edx-proctoring to be upgraded with django 3.2 in the coming months.

**Comment by jmbowman** [comment]
Given that edx-proctoring-proctortrack doesn't even have a test suite yet, I think we'll need to just rely on the edx-proctoring and edx-platform test suites to verify that this is working correctly when we upgrade.  I'll close this and update our upgrade notes accordingly.
